# Generated by Django 2.2.24 on 2022-05-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20220503_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='_flat_liked_by_+', to='property.User', verbose_name='Понравилось пользователям'),
        ),
    ]
